  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "ブログ"
  weight = 200
  identifier = "posts"
  url = "/blog/"

  [[main]]
  name = "カテゴリー"
  weight = 300
  identifier = "categories"
  url = "/categories/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"
