---
title: Haruk.Xyz
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  "-content-japanese-post":
    title: japanese
    output: true
    permalink: "/post"
