---
title: Haruk.Xyz
timezone: UTC
collections:
  content-japanese-post:
    title: Posts
    output: true
  post:
    title: Posts
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
